const data = {
  "product":[
    {
      id: 1,
      title: "Cây Trầu bà",
      category: "Cây cảnh để bàn",
      price: 20000,
      img: "./images/item-1.jpg",
      desc: `Cây thân thảo, dạng leo, lá đơn, gốc lá hình tim, thuôn dài ở đỉnh, có loại xanh toàn phần, có loại có những đốm vàng trên lá, vàng nằm rải rác trên phiến lá, cụm hoa dạng mo, cuống ngắn, bò dài hoặc buông thõng xuống trên các chậu treo `,
    },
    {
      id: 2,
      title: "Cây Vạn lộc",
      category: "Cây cảnh để bàn",
      price: 200000,
      img: "./images/item-2.jpg",
      desc: `Là giống cây thân thảo, có nguồn gốc từ Thái Lan, Indonesia, có lá mọc từ gốc, có lá màu hồng nhạt và đậm dần theo thời gian, viền xung quanh màu xanh, lá dày, gân nổi rõ. `,
    },
    {
      id: 3,
      title: "Cây Tùng hạnh phúc",
      category: "Cây cảnh để bàn",
      price: 160000,
      img: "./images/item-3.jpg",
      desc: `Mang ý nghĩa cầu chúc mọi điềm lành trong cuộc sống, phù hợp chưng trong nhà, văn phòng, bàn làm việc hoặc trên giá, trên kệ, làm quà tặng.`,
    },
    {
      id: 4,
      title: "Cây Vạn niên thanh",
      category: "Cây cảnh nội thất",
      price: 500000,
      img: "./images/item-4.jpg",
      desc: `Thuộc loại cây thân thảo, có rễ chùm ngắn, mập. Lá cây đặc biệt với màu trắng gần gân lá nổi bật trên nền xanh của lá. Lá mềm, xanh quanh năm, khi bẹ lá rụng để lại một vòng xung quanh thân cây. Cây trồng văn phòng thường có chiều cao từ 40-100 cm. Cây để bàn có chiều cao khoảng 15-35 cm.`,
    },
    {
      id: 5,
      title: "Cây Tùng sơn",
      category: "Cây cảnh nội thất",
      price: 190000,
      img: "./images/item-5.jpg",
      desc: `Là giống cây thuộc họ lá kim, kiểu dáng chủ yếu của nó là hình tháp được bao phủ xung quanh là lớp lá xanh tươi, cứng cỏi. Đây là loại cây phát triển chậm nên kích thước cây thường không quá lớn. Cây có chiều cao khoảng từ 30 - 60 cm (có thể cao đến 1m). `,
    },
    {
      id: 6,
      title: "Cây Tùng bồng lai",
      category: "Cây cảnh nội thất",
      price: 320000,
      img: "./images/item-6.png",
      desc: `Là loại cây thân gỗ kích thước nhỏ. Chiều cao trung bình của cây chỉ khoảng 40 cm cầm rất tiện tay và dễ di chuyển. Cây thuộc nhóm cây lâu năm nên có tuổi thọ rất cao. Lá cây tùng bồng lai mọc rất nhiều và dày đặc với nhau có dạng lá kim nhỏ, dài và nhọn ở phía đầu lá. Màu sắc của lá cây là màu xanh bóng, sờ có cảm giác cứng`,
    },
    {
      id: 7,
      title: "Cây Cọ Nhật",
      category: "Cây cảnh ngoại thất",
      price: 550000,
      img: "./images/item-7.jpg",
      desc: `Là cây thân gỗ thuộc họ Cau, có nguồn gốc từ các nước ôn đới, sau đó lan dần ra nhiều nước khác trong đó có Việt Nam.`,
    },
    {
      id: 8,
      title: "Cây Bông bụt Thái",
      category: "Cây cảnh ngoại thất",
      price: 250000,
      img: "./images/item-8.png",
      desc: `Là cây thuộc loại cây bụi lớn, nếu được trồng trong điều kiện thích hợp cây có thể cao đến 4-5 m. Cây phát triển không theo hướng cố định, có cây mọc thẳng nhưng cũng có cây mọc xiên lan rộng ra xung quanh. `,
    },
    {
      id: 9,
      title: "Cây Đại phú gia",
      category: "Cây cảnh ngoại thất",
      price: 700000,
      img: "./images/item-9.jpg",
      desc: `Cây có màu xanh thẫm, thân cây mập lùn có đốt quanh thân cây, lá cây tập trung ở ngọn. Lá cây có hình bầu dục hơi nhọn ở đầu lá, lá cây có màu xanh bóng pha chút ánh vàng khi nhìn từ xa. Cuống lá mập, bẹ ôm lấy thân cây và cũng có màu xanh. Cây ra hoa màu trắng ngà, hoa dài và hướng lên trời có mùi thơm khá nồng.`,
    },
    {
      id: 10,
      title: "Cây Nhất chi mai",
      category: "Cây bonsai",
      price: 190000,
      img: "./images/item-10.jpg",
      desc: `Phát triển tương đối chậm, chúng chỉ xuất hiện ở những nơi có mùa đông lạnh giá, tuyết phủ trắng xóa. Gốc cây xù xì, thân đen óng cổ thụ. Nụ hoa màu đỏ nhưng khi nở lại có màu trắng và rồi lại trở về màu đỏ khi đã tàn phai.`,
    },
    {
      id: 11,
      title: "Cây Đa bonsai",
      category: "Cây bonsai",
      price: 200000,
      img: "./images/item-11.jpg",
      desc: `Là cây thân gỗ nhưng dễ dàng uốn cong tạo hình. Cây có màu nâu, lá cây hơi thuôn, dạng elip hoặc quả trứng, mép nguyên, mặt trên bóng, màu xanh. Chiều cao: 30 - 60 cm (tính cả chậu).`,
    },
    {
      id: 12,
      title: "Cây Kim ngân củ",
      category: "Cây bonsai",
      price: 900000,
      img: "./images/item-12.jpg",
      desc: `Có nguồn gốc từ Trung Mỹ và Nam Mỹ. Cây chỉ có 1 thân duy nhất, thân to và ngắn tạo thành một khối tròn hình củ. Thây cây non có màu xanh sáng, khi già chuyển sang màu xám trắng. Lá cây màu xanh đậm, cuống lá gồm 5 lá hình thù như chân chim.`,
    },
    {
      id: 13,
      title: "Cây Khế",
      category: "Cây ăn trái",
      price: 600000,
      img: "./images/item-13.jpg",
      desc: `Cây Khế là loại cây truyền thống của Việt Nam được trồng từ nhiều đời nay với nhiều công dụng, cho hoa đẹp, quả ngon, cây có nhiều dáng thế để làm cảnh nên rất được ưa chuộng.`,
    },
    {
      id: 14,
      title: "Cây Ổi",
      category: "Cây ăn trái",
      price: 300000,
      img: "./images/item-14.jpg",
      desc: `Cây Ổi là giống cây ăn quả có từ lâu đời. Đây là loài thực vật vốn có nguồn gốc từ Brazil, được phát hiện lần đầu vào năm 1753 bởi các nhà thực vật học. Sau này cây ổi được phổ biến rộng rãi trên toàn thế giới và trở thành một trong những loại cây ăn quả hàng đầu rất được ưa chuộng.`,
    },
    {
      id: 15,
      title: "Cây Cóc",
      category: "Cây ăn trái",
      price: 150000,
      img: "./images/item-15.jpg",
      desc: `Cây cóc là giống cây ăn quả, vị thơm ngon, giòn giòn, chua dịu, hấp dẫn, khả năng ra hoa quả quanh năm, sai trĩu cành khiến cóc trở thành loại cây ăn quả được trồng nhiều trong nhà phố.`,
    },
  ],
  "footerInfo": [
    {
      name : "Cửa hàng cây cảnh T&H",
      address : "Địa chỉ: Số 1 Phùng Chí Kiên, Cầu Giấy, Hà Nội",
      phone : "Số điện thoại: 0978993393",
      mail : "hanhthuy83@gmail.com"
    }
  ]
}  
export default data;
